server:
  port: 8080
---

spring:
  profiles: https
server:
  port: 8443
  ssl:
    enabled: true
    key-alias: ${SSL_KEY_ALIAS}
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-type: ${SSL_KEYSTORE_TYPE}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
